name: HeroicChat
main: heroicchat.main.HeroicChat
author: Sgt_Tailor
description: A Heroic chat plugin
version: 0.1
commands:
    heroicchat:
        aliases: [hc, heroicc]
        usage: /heroicchat
permissions:
    heroicchat.channel.bypasslock:
        default: OP
    heroicchat.player.kick:
        default: OP
    heroicchat.channel.edit.own:
        default: true
    heroicchat.channel.edit.all:
        default: OP